Migrate to google test framework
ostis-dev/sc-machine pull request #320
Opened 2020-10-18 22:21 UTC by deniskoronchik

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

Resolves: #314

2020-11-03 16:34 UTC, MikhailSadovsky requested changes
"Unit tests" documentation section should be updated as it will become obsolete after these changes

2020-11-06 06:10 UTC, ValikVityaz requested changes
Minor formatting issues

2020-11-06 06:10 UTC, ValikVityaz commented on sc-memory/tests/scs/units/test_scs_level_6.cpp
> +
```suggestion
```

2020-11-10 09:36 UTC, ValikVityaz approved these changes

2020-11-10 10:13 UTC, MikhailSadovsky approved these changes

2020-11-11 11:56 UTC, KovalM approved these changes

2020-11-11 16:59 UTC, merged