Add Mint-specific instructions
ostis-dev/sc-machine pull request #328
Opened 2020-11-01 14:57 UTC by ValikVityaz

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

2020-11-01 15:00 UTC, ValikVityaz commented on README.md
> -Install Python development package
Not required to do manually as it is installed as a dependency of libboost-python-dev.

2020-11-01 19:25 UTC, deniskoronchik commented
Do not try to reuse some line in this document, let's do different sections:

## Build on Ubuntu

## Build on Mint

... and this section should contain full Mint instruction even some of parts will duplicate Ubuntu one. It will be easier for users and support

2020-11-01 19:25 UTC, deniskoronchik requested changes
More clean structure

2020-11-04 10:19 UTC, deniskoronchik approved these changes

2020-11-05 14:37 UTC, deniskoronchik commented
Fixup review fixes commits into one: "Review fixes"

2020-11-05 14:37 UTC, deniskoronchik requested changes
Fixup

2020-11-05 14:40 UTC, KovalM approved these changes

2020-11-05 17:02 UTC, deniskoronchik approved these changes

2020-11-05 17:07 UTC, merged