Add a link content check before removing it from storage
ostis-dev/sc-machine pull request #344
Opened 2020-11-20 09:41 UTC by ValikVityaz

fixes #341

2020-11-20 15:54 UTC, deniskoronchik commented on sc-memory/sc-core/sc-store/sc_storage.c
> +      if (sc_element_is_checksum_empty(el) == SC_FALSE) {
```suggestion
      if (sc_element_is_checksum_empty(el) == SC_FALSE) 
      {
```

2020-11-20 15:54 UTC, deniskoronchik commented on sc-memory/tests/sc-memory/common/sc-link.cpp
> +TEST_F(ScLinkTest, erase) {
```suggestion
TEST_F(ScLinkTest, erase)
{
```

2020-11-20 15:56 UTC, deniskoronchik requested changes
codestyle

2020-11-20 15:56 UTC, deniskoronchik commented
Update changelog

2020-11-20 15:58 UTC, deniskoronchik commented on sc-memory/tests/sc-memory/common/sc-link.cpp
> +  ScMemoryContext ctx(sc_access_lvl_make_min, "sc_link_erase");
Use `m_ctx` instead

2020-11-23 09:05 UTC, KovalM approved these changes

2020-11-23 11:25 UTC, deniskoronchik approved these changes

2020-11-23 14:01 UTC, MikhailSadovsky approved these changes

2020-11-24 08:11 UTC, merged