Web
ostis-dev/sc-machine pull request #370
Opened 2020-12-20 21:51 UTC by deniskoronchik

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

2020-12-25 17:08 UTC, MikhailSadovsky requested changes

2020-12-25 17:09 UTC, MikhailSadovsky commented
Small formatting corrections

2020-12-28 07:29 UTC, MikhailSadovsky approved these changes

2020-12-28 09:08 UTC, KovalM approved these changes

2020-12-28 12:17 UTC, merged