Implement new template API
ostis-dev/sc-machine pull request #374
Opened 2020-12-21 23:07 UTC by deniskoronchik

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

Resolves: #367

2021-02-07 22:36 UTC, KovalM requested changes

2021-02-08 08:22 UTC, ValikVityaz requested changes

2021-02-08 12:25 UTC, MikhailSadovsky requested changes

2021-02-08 12:25 UTC, MikhailSadovsky commented on docs/cpp/templates.md
> +ScTemplateSeach search(ctx, *templ);
```suggestion
ScTemplateSearch search(ctx, *templ);
```

2021-02-08 12:25 UTC, MikhailSadovsky commented on docs/cpp/templates.md
> +ScTemplateSeach search(ctx, *templ, params);
```suggestion
ScTemplateSearch search(ctx, *templ, params);
```

2021-02-08 12:25 UTC, MikhailSadovsky commented on docs/cpp/templates.md
> +Search engine traverses cs-memory to find all contructions that correspond to template. Let's assume that we need to check if specified sc-element (`_device`) is included into `device` set and `devic
```suggestion
Search engine traverses sc-memory to find all contructions that correspond to template. Let's assume that we need to check if specified sc-element (`_device`) is included into `device` set and `device_enabled` set:
```

2021-02-08 14:30 UTC, deniskoronchik commented on sc-memory/sc-memory/sc_template_search.hpp
> +    Iterator & operator ++ ();
#391

2021-02-08 14:32 UTC, deniskoronchik commented on sc-memory/sc-memory/sc_template_builder.hpp
> +  _SC_EXTERN ScTemplatePtr Make();
```cpp
ScTemplateBuilder builder;

builder.build(); // ?
```

2021-02-08 14:41 UTC, deniskoronchik commented on sc-memory/sc-memory/sc_template_builder_impl.hpp
> +  * \remarks Do not use builde after this method call.
Fixed to: `* \remarks Do not use builder after this method call.`

This comment talks to do not use builder (call any function) after this functions call.

2021-02-08 16:11 UTC, KovalM commented on sc-memory/sc-memory/sc_template_builder.hpp
> +  _SC_EXTERN ScTemplatePtr Make();
Yes

2021-02-08 16:13 UTC, KovalM approved these changes

2021-02-08 16:17 UTC, MikhailSadovsky approved these changes

2021-02-08 16:20 UTC, deniskoronchik commented on sc-memory/sc-memory/sc_template_builder.hpp
> +  _SC_EXTERN ScTemplatePtr Make();
We can discuss that later. I don't see any problems with current name. And don't understand why new one will be better. The main idea of this name was, that building of template is going during `Tirple...` method calls. These methods can raise an exception. And `Make` method produce a final pointer to builded template.

Also it was similar to make_unique, make_shared in std library

2021-02-09 09:29 UTC, KovalM commented on sc-memory/sc-memory/sc_template_builder.hpp
> +  _SC_EXTERN ScTemplatePtr Make();
My single argument was popularity of the method's name "build" among developers, but I investigate cpp code from different projects and found that is not so popular as I thought. This name so popular among Java developers. I am ready to resolve this conversation.

2021-02-09 16:03 UTC, ValikVityaz approved these changes

2021-02-09 16:04 UTC, merged