[ci] Migrate to github actions
ostis-dev/sc-machine pull request #383
Opened 2021-01-04 19:45 UTC by deniskoronchik

* [ ] Read PR [documentation](http://ostis-dev.github.io/sc-machine/dev/pr/)
* [ ] Update changelog
* [ ] Update documentation

2021-01-05 21:04 UTC, MikhailSadovsky requested changes

2021-01-05 21:05 UTC, MikhailSadovsky commented
Please update `Build Status` link for `README` file

2021-01-05 21:35 UTC, deniskoronchik commented on scripts/ci/install-tests.sh
> +cmake .. -DCMAKE_BUILD_TYPE=${BUILD_TYPE} -DSC_AUTO_TEST=ON -DSC_BUILD_SCTP=OFF -DBUILD_TESTING=ON -DSC_KPM_SCP=OFF
Two reasons:
1. Qt5 depend on package that is not exist in azure mirror of ubuntu packages and can't be installed in github actions environment
2. We will replace it soon with new protocol

So it's much easier to disable it, then support for this period

2021-01-13 13:33 UTC, MikhailSadovsky approved these changes

2021-01-13 13:34 UTC, merged